package research

import (
	"context"
	"fmt"
	"strings"
	"sync"
	"time"

	"github.com/KyberixCo/Pharus/internal/llm"
)

// GlobalInsight is a finding kept by DataSTORM. A finding is never considered
// validated solely because it was generated by an LLM: it must identify either
// the evidence item from which it was extracted or the structured query that
// produced it.
type GlobalInsight struct {
	ID               string    `json:"id"`
	Topic            string    `json:"topic"`
	Thesis           string    `json:"thesis"`
	Metric           string    `json:"metric"`
	Source           string    `json:"source"`
	SourceType       string    `json:"source_type"`
	EvidenceID       string    `json:"evidence_id,omitempty"`
	StructuredQuery  string    `json:"structured_query,omitempty"`
	ValidationStatus string    `json:"validation_status"`
	Timestamp        time.Time `json:"timestamp"`
}

const (
	InsightSourceEvidence       = "evidence"
	InsightSourceStructuredData = "structured_data"
	InsightValidationEvidence   = "evidence_linked"
	InsightValidationStructured = "structured_validated"
	InsightValidationUnverified = "unverified"
)

// HasValidProvenance reports whether a finding can safely be included in a
// synthesis prompt. In particular, text generated without an evidence ID must
// not be described as verified evidence.
func (ins *GlobalInsight) HasValidProvenance() bool {
	if ins == nil || strings.TrimSpace(ins.Source) == "" {
		return false
	}
	switch ins.SourceType {
	case InsightSourceEvidence:
		return strings.TrimSpace(ins.EvidenceID) != "" && ins.ValidationStatus == InsightValidationEvidence
	case InsightSourceStructuredData:
		return strings.TrimSpace(ins.StructuredQuery) != "" && ins.ValidationStatus == InsightValidationStructured
	default:
		return false
	}
}

// GlobalInsightBank is a thread-safe repository storing global insights across concurrent research threads.
type GlobalInsightBank struct {
	mu       sync.RWMutex
	insights map[string]*GlobalInsight
}

func NewGlobalInsightBank() *GlobalInsightBank {
	return &GlobalInsightBank{
		insights: make(map[string]*GlobalInsight),
	}
}

func (bank *GlobalInsightBank) AddInsight(insight *GlobalInsight) {
	if insight == nil {
		return
	}
	bank.mu.Lock()
	defer bank.mu.Unlock()

	if insight.Timestamp.IsZero() {
		insight.Timestamp = time.Now()
	}
	if insight.ID == "" {
		insight.ID = fmt.Sprintf("ins_%d", len(bank.insights)+1)
	}
	bank.insights[insight.ID] = insight
}

func (bank *GlobalInsightBank) GetInsightsForTopic(topic string) []*GlobalInsight {
	bank.mu.RLock()
	defer bank.mu.RUnlock()

	var result []*GlobalInsight
	topicLower := strings.ToLower(topic)
	for _, ins := range bank.insights {
		if strings.Contains(strings.ToLower(ins.Topic), topicLower) || strings.Contains(topicLower, strings.ToLower(ins.Topic)) {
			result = append(result, ins)
		}
	}
	return result
}

func (bank *GlobalInsightBank) GetAllInsights() []*GlobalInsight {
	bank.mu.RLock()
	defer bank.mu.RUnlock()

	result := make([]*GlobalInsight, 0, len(bank.insights))
	for _, ins := range bank.insights {
		result = append(result, ins)
	}
	return result
}

// ExtractInsightsFromEvidence extracts findings while retaining the precise
// evidence item that supports them.
func (bank *GlobalInsightBank) ExtractInsightsFromEvidence(ctx context.Context, llmClient llm.Provider, topic string, evidence Evidence) ([]*GlobalInsight, error) {
	return bank.extractInsightsFromText(ctx, llmClient, topic, evidence.Content, evidence.CanonicalURL, evidence.ID)
}

// ExtractInsightsFromText extracts key domain postulations, metrics, or theses from evidence text using LLM or heuristics.
//
// Deprecated: callers processing research evidence should use
// ExtractInsightsFromEvidence. This compatibility helper intentionally creates
// unverified findings, which are excluded from synthesis.
func (bank *GlobalInsightBank) ExtractInsightsFromText(ctx context.Context, llmClient llm.Provider, topic string, text string, source string) ([]*GlobalInsight, error) {
	return bank.extractInsightsFromText(ctx, llmClient, topic, text, source, "")
}

func (bank *GlobalInsightBank) extractInsightsFromText(ctx context.Context, llmClient llm.Provider, topic string, text string, source string, evidenceID string) ([]*GlobalInsight, error) {
	if text == "" {
		return nil, nil
	}

	var extracted []*GlobalInsight

	if llmClient != nil {
		snippet := text
		if len(snippet) > 1500 {
			snippet = snippet[:1500]
		}

		promptTemplate := researchText(ctx, `Given this text from source "%s" about topic "%s":
"%s"

Extract up to two verified key findings or quantitative metrics (DataSTORM).
Strict format, one per line:
Main Thesis or Claim | Metric or Quantitative Datum`, `Dado el siguiente texto de la fuente "%s" sobre el tema "%s":
"%s"

Extrae hasta 2 hallazgos clave o métricas cuantitativas verificadas (DataSTORM).
Formato estricto por línea:
Tesis u Afirmación Principal | Métrica o Dato Cuantitativo`)
		prompt := fmt.Sprintf(promptTemplate, source, topic, snippet)

		messages := []llm.Message{
			{Role: "system", Content: researchText(ctx,
				"You are a DataSTORM findings extractor focused on identifying key metrics and analytical claims.",
				"Eres un extractor de hallazgos DataSTORM enfocado en identificar métricas y postulados analíticos clave.",
			) + "\n\n" + reportLanguageDirective(ctx)},
			{Role: "user", Content: prompt},
		}

		resp, err := llmClient.GenerateCompletion(ctx, messages, 0.2)
		if err == nil && resp != "" {
			lines := strings.Split(resp, "\n")
			for i, line := range lines {
				parts := strings.Split(line, "|")
				if len(parts) >= 2 {
					thesis := strings.TrimSpace(parts[0])
					metric := strings.TrimSpace(parts[1])
					if thesis != "" {
						ins := &GlobalInsight{
							ID:               fmt.Sprintf("ins_auto_%d_%d", time.Now().UnixNano(), i),
							Topic:            topic,
							Thesis:           thesis,
							Metric:           metric,
							Source:           source,
							SourceType:       InsightSourceEvidence,
							EvidenceID:       evidenceID,
							ValidationStatus: insightValidationForEvidence(evidenceID),
							Timestamp:        time.Now(),
						}
						bank.AddInsight(ins)
						extracted = append(extracted, ins)
					}
				}
			}
		}
	}

	// Fallback heuristic if LLM didn't produce insights or is nil
	if len(extracted) == 0 && len(text) > 20 {
		firstLine := strings.Split(text, "\n")[0]
		if len(firstLine) > 100 {
			firstLine = firstLine[:100]
		}
		ins := &GlobalInsight{
			ID:               fmt.Sprintf("ins_heur_%d", time.Now().UnixNano()),
			Topic:            topic,
			Thesis:           firstLine,
			Metric:           fmt.Sprintf("Fuente: %s", source),
			Source:           source,
			SourceType:       InsightSourceEvidence,
			EvidenceID:       evidenceID,
			ValidationStatus: insightValidationForEvidence(evidenceID),
			Timestamp:        time.Now(),
		}
		bank.AddInsight(ins)
		extracted = append(extracted, ins)
	}

	return extracted, nil
}

func insightValidationForEvidence(evidenceID string) string {
	if strings.TrimSpace(evidenceID) == "" {
		return InsightValidationUnverified
	}
	return InsightValidationEvidence
}

// QueryConsistencyDetector intercepts search and analytical queries across concurrent threads,
// comparing them with the GlobalInsightBank to eliminate bias or logical divergence.
type QueryConsistencyDetector struct {
	bank *GlobalInsightBank
}

func NewQueryConsistencyDetector(bank *GlobalInsightBank) *QueryConsistencyDetector {
	return &QueryConsistencyDetector{bank: bank}
}

// ValidateAndAlignQuery checks if a query contains conflicting or biased premises compared to global insights,
// returning an aligned query if divergence is detected.
func (d *QueryConsistencyDetector) ValidateAndAlignQuery(ctx context.Context, topic string, query string) (string, bool) {
	insights := d.bank.GetInsightsForTopic(topic)
	if len(insights) == 0 {
		return query, true // No stored insights to conflict with
	}

	alignedQuery := query
	adjusted := false

	queryLower := strings.ToLower(query)
	divergentTerms := []string{"override", "ignorar", "contradice", "falso", "sin validar"}

	// Check if query contradicts core global metrics/hypotheses or uses divergent terms
	for _, ins := range insights {
		hasDivergence := false
		for _, term := range divergentTerms {
			if strings.Contains(queryLower, term) {
				hasDivergence = true
				break
			}
		}

		if ins.Metric != "" && hasDivergence {
			alignedQuery = fmt.Sprintf("%s (validado contra %s)", query, ins.Metric)
			adjusted = true
			break
		}
	}

	return alignedQuery, !adjusted
}

// ValidateAndAlignSQLQuery checks structured SQL queries for logical divergence, biased filters, or destructive clauses.
func (d *QueryConsistencyDetector) ValidateAndAlignSQLQuery(ctx context.Context, topic string, sqlQuery string) (string, bool) {
	sqlLower := strings.ToLower(sqlQuery)

	// Direct safety check against destructive or invalid SQL syntax
	destructiveKeywords := []string{"drop ", "delete ", "truncate ", "update ", "insert "}
	for _, kw := range destructiveKeywords {
		if strings.Contains(sqlLower, kw) {
			// Convert to safe SELECT query
			return fmt.Sprintf("SELECT * FROM research_metrics WHERE topic LIKE '%%%s%%'", topic), false
		}
	}

	// Check for divergent logical clauses (e.g. 1=0 or override attempts)
	if strings.Contains(sqlLower, "1=0") || strings.Contains(sqlLower, "where status = 'unvalidated'") {
		alignedSQL := strings.ReplaceAll(sqlQuery, "1=0", "1=1")
		alignedSQL = strings.ReplaceAll(alignedSQL, "status = 'unvalidated'", "status = 'validated'")
		return alignedSQL, false
	}

	// Align parameters with GlobalInsight metrics if available
	insights := d.bank.GetInsightsForTopic(topic)
	if len(insights) > 0 {
		for _, ins := range insights {
			if ins.Metric != "" && strings.Contains(sqlLower, "where") && !strings.Contains(sqlLower, "metric") {
				// Inject metric baseline context into query condition
				return fmt.Sprintf("%s AND (metric_note = '%s' OR 1=1)", sqlQuery, ins.Metric), false
			}
		}
	}

	return sqlQuery, true
}

// SQLQueryResult represents structured analytical findings from a DataSTORM relational query.
type SQLQueryResult struct {
	Columns       []string   `json:"columns"`
	Rows          [][]string `json:"rows"`
	MetricSummary string     `json:"metric_summary"`
	QueryExecuted string     `json:"query_executed"`
	RowCount      int        `json:"row_count"`
}

// StructuredDataProvider defines the contract for executing analytical SQL queries over structured data.
type StructuredDataProvider interface {
	ExecuteSQL(ctx context.Context, query string) (*SQLQueryResult, error)
	GetSchema(ctx context.Context) (string, error)
}

// InMemorySQLProvider is a lightweight Pure-Go relational data engine for DataSTORM exploratory analysis.
type InMemorySQLProvider struct {
	mu     sync.RWMutex
	tables map[string]*SQLQueryResult
}

func NewInMemorySQLProvider() *InMemorySQLProvider {
	return &InMemorySQLProvider{tables: make(map[string]*SQLQueryResult)}
}

// AddTable loads explicitly supplied data. It exists for tests and explicit
// demo modes; production never populates this provider implicitly.
func (p *InMemorySQLProvider) AddTable(name string, table SQLQueryResult) {
	p.mu.Lock()
	defer p.mu.Unlock()
	table.Columns = append([]string(nil), table.Columns...)
	table.Rows = append([][]string(nil), table.Rows...)
	table.RowCount = len(table.Rows)
	p.tables[name] = &table
}

func (p *InMemorySQLProvider) GetSchema(ctx context.Context) (string, error) {
	p.mu.RLock()
	defer p.mu.RUnlock()

	var sb strings.Builder
	sb.WriteString("Esquemas Relacionales Disponibles (DataSTORM):\n")
	for name, table := range p.tables {
		sb.WriteString(fmt.Sprintf("- Tabla: %s (Columnas: %s, Registros: %d)\n", name, strings.Join(table.Columns, ", "), table.RowCount))
	}
	return sb.String(), nil
}

func (p *InMemorySQLProvider) ExecuteSQL(ctx context.Context, query string) (*SQLQueryResult, error) {
	p.mu.RLock()
	defer p.mu.RUnlock()

	// Simple SQL execution engine supporting SELECT queries
	sqlLower := strings.ToLower(query)
	tableName := ""

	for tName := range p.tables {
		if strings.Contains(sqlLower, tName) {
			tableName = tName
			break
		}
	}

	table, exists := p.tables[tableName]
	if !exists {
		return &SQLQueryResult{
			Columns:       []string{"info"},
			Rows:          [][]string{{"No records found for query"}},
			MetricSummary: "Consulta finalizada sin resultados tabulares",
			QueryExecuted: query,
			RowCount:      0,
		}, nil
	}

	// Filter rows based on topic or condition if present
	var filteredRows [][]string
	for _, row := range table.Rows {
		match := true
		if strings.Contains(sqlLower, "where") {
			// Check if any row item matches terms in query
			rowMatch := false
			for _, val := range row {
				if strings.Contains(sqlLower, strings.ToLower(val)) {
					rowMatch = true
					break
				}
			}
			if !rowMatch && !strings.Contains(sqlLower, "1=1") {
				match = false
			}
		}

		if match {
			filteredRows = append(filteredRows, row)
		}
	}

	summary := fmt.Sprintf("DataSTORM SQL ejecutado exitosamente (%d filas devueltas)", len(filteredRows))
	return &SQLQueryResult{
		Columns:       table.Columns,
		Rows:          filteredRows,
		MetricSummary: summary,
		QueryExecuted: query,
		RowCount:      len(filteredRows),
	}, nil
}

// DataSTORMAnalyzer orchestrates exploratory data analysis, hypothesis cross-validation, and query alignment.
type DataSTORMAnalyzer struct {
	bank         *GlobalInsightBank
	detector     *QueryConsistencyDetector
	dataProvider StructuredDataProvider
	llm          llm.Provider
}

func NewDataSTORMAnalyzer(bank *GlobalInsightBank, provider StructuredDataProvider, llmClient llm.Provider) *DataSTORMAnalyzer {
	return &DataSTORMAnalyzer{
		bank:         bank,
		detector:     NewQueryConsistencyDetector(bank),
		dataProvider: provider,
		llm:          llmClient,
	}
}

// Enabled reports whether an explicitly configured structured-data source is
// available. DataSTORM is optional and must stay off without one.
func (a *DataSTORMAnalyzer) Enabled() bool {
	return a != nil && a.dataProvider != nil
}

func (a *DataSTORMAnalyzer) ExploreHypothesis(ctx context.Context, topic string, hypothesis string) (*SQLQueryResult, []*GlobalInsight, error) {
	if !a.Enabled() {
		return nil, nil, nil
	}
	// 1. Formulate SQL analytical query from hypothesis
	sqlQuery := fmt.Sprintf("SELECT * FROM research_metrics WHERE topic LIKE '%%%s%%'", topic)
	if a.llm != nil {
		schema, _ := a.dataProvider.GetSchema(ctx)
		promptTemplate := researchText(ctx, `Given this relational database schema:
%s

And the research hypothesis: "%s" (Topic: "%s")

Generate a simple SQL SELECT query to validate the hypothesis. Return ONLY the SQL statement on one line.`, `Dado el esquema de base de datos relacional:
%s

Y la hipótesis de investigación: "%s" (Tema: "%s")

Genera una consulta SQL SELECT simple para validar la hipótesis. Devuelve SOLAMENTE la sentencia SQL en una sola línea.`)
		prompt := fmt.Sprintf(promptTemplate, schema, hypothesis, topic)

		messages := []llm.Message{
			{Role: "system", Content: researchText(ctx,
				"You are a DataSTORM SQL query generator for exploratory data analysis.",
				"Eres un generador de consultas SQL DataSTORM para análisis exploratorio de datos.",
			) + "\n\n" + reportLanguageDirective(ctx)},
			{Role: "user", Content: prompt},
		}

		resp, err := a.llm.GenerateCompletion(ctx, messages, 0.2)
		if err == nil && strings.HasPrefix(strings.ToUpper(strings.TrimSpace(resp)), "SELECT") {
			sqlQuery = strings.TrimSpace(resp)
		}
	}

	// 2. Validate & Align SQL Query Consistency against Global Insight Bank
	alignedSQL, _ := a.detector.ValidateAndAlignSQLQuery(ctx, topic, sqlQuery)

	// 3. Execute analytical query
	result, err := a.dataProvider.ExecuteSQL(ctx, alignedSQL)
	if err != nil {
		return nil, nil, fmt.Errorf("datastorm query execution failed: %w", err)
	}

	// 4. Extract structured insights from query results and record in GlobalInsightBank
	var newInsights []*GlobalInsight
	if result.RowCount > 0 {
		for i, row := range result.Rows {
			rowStr := strings.Join(row, " | ")
			ins := &GlobalInsight{
				ID:               fmt.Sprintf("ins_datastorm_%d_%d", time.Now().UnixNano(), i),
				Topic:            topic,
				Thesis:           fmt.Sprintf("Validación DataSTORM para hipótesis '%s'", hypothesis),
				Metric:           fmt.Sprintf("Datos Relacionales: [%s]", rowStr),
				Source:           fmt.Sprintf("DataSTORM SQL (%s)", result.QueryExecuted),
				SourceType:       InsightSourceStructuredData,
				StructuredQuery:  result.QueryExecuted,
				ValidationStatus: InsightValidationStructured,
				Timestamp:        time.Now(),
			}
			a.bank.AddInsight(ins)
			newInsights = append(newInsights, ins)
		}
	}

	return result, newInsights, nil
}
